# Generated by Django 6.1 on 2026-08-19 18:10

import django.db.models.deletion
import pgvector.django.vector
from pgvector.django import VectorExtension
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('iab_categories', models.JSONField(default=list)),
                ('target_tone', models.CharField(blank=True, max_length=64)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['brand', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('source_url', models.URLField(blank=True)),
                ('file_key', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('has_audio', models.BooleanField(blank=True, null=True)),
                ('scenes_total', models.IntegerField(default=0)),
                ('scenes_done', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('start', models.FloatField()),
                ('end', models.FloatField()),
                ('keyframe_keys', models.JSONField(default=list)),
                ('transcript_text', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('objects_seen', models.JSONField(default=list)),
                ('tone', models.CharField(blank=True, max_length=64)),
                ('iab_categories', models.JSONField(default=list)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True)),
                ('brand_safety_flag', models.BooleanField(default=False)),
                ('top_matches', models.JSONField(default=list)),
                ('recommended_ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ad')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='core.video')),
            ],
            options={
                'ordering': ['video', 'index'],
                'constraints': [models.UniqueConstraint(fields=('video', 'index'), name='unique_scene_index')],
            },
        ),
    ]
