
services:
  context_ai_django:
    env_file:
      - path: ../../.env
        required: true
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/context_ai
      REDIS_URL: redis://redis:6379/0
      CELERY_WORKER_POOL: prefork
    build:
      context: ../..
      dockerfile: ./docker/nonprod/Dockerfile
      args:
        - USER=${USER}
    volumes:
      - ../..:/backend
      - ${HOME}/.ssh:/home/${USER}/.ssh
      - model_cache:/home/${USER}/.cache
    ports:
      - 8022:8000
    container_name: context_ai_backend_nonprod
    networks:
      - backend
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  model_cache:

networks:
  backend:
    name: backend_default
    external: true
